# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np

In [4]:
my_arr = np.arange(0,20,2)
my_arr
ray= np.array((4,4,4,4,4))

In [6]:
# The code below will add corresponding elements of two arrays
my_arr + my_arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [4]:
#The code below will multiply corresponding elements of two arrays
my_arr * my_arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [11]:
mat_1= [[1,2,3],[4,5,6],[7,8,9]]
mat_2= [3,5,10]

In [12]:
# we can do scalar multiplication of two arrays which multiplies corresponding elements of both arrays
mul= np.array(mat_1)*np.array(mat_2)
mul

array([[ 3, 10, 30],
       [12, 25, 60],
       [21, 40, 90]])

In [13]:
# the dot function does the vector or dot product of two arrays; note how this is different from scalar product
mat1=np.array(mat_1)
mat2=np.array(mat_2)
matmul1=mat1.dot(mat2)
matmul1

array([ 43,  97, 151])

In [14]:
matmul2=mat2.dot(mat1)
matmul2

array([ 93, 111, 129])

In [9]:
# The matmul function in numpy also does the vector product of two arrays
np.matmul(mat1,mat2)

array([ 43,  97, 151])

In [10]:
np.matmul(mat2,mat1)

array([ 93, 111, 129])

In [11]:
# The code below finds the cube of each element in the array
my_arr**3

array([   0,    8,   64,  216,  512, 1000, 1728, 2744, 4096, 5832],
      dtype=int32)

In [12]:
# The code below finds the square root of each element in the array
np.sqrt(my_arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

# NumPy Indexing and Selection

This deals with how to select elements or groups of elements from an array.

In [13]:
my_arr[3]

6

In [14]:
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#to get values within an index range:
my_arr[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
##change values with an index range:
my_arr[2:5]= 50
my_arr

array([ 0,  2, 50, 50, 50, 10, 12, 14, 16, 18])

In [15]:
my_arr= np.arange(0,20,2)

In [18]:
##to get a slice of the array:
Zainab_array= my_arr[0:5]

In [20]:
Zainab_array

array([0, 2, 4, 6, 8])

In [31]:
slice_of_my_arr[:]=100
slice_of_my_arr

array([100, 100, 100, 100, 100])

In [30]:
##changes we made to array slice will also appear in original array
my_arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18])

## Indexing a 2D array (matrices)

In [37]:
my_mat = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
my_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
#Indexing row
my_mat[1]

array([20, 25, 30])

In [42]:
#indexing column
my_mat[:1,:2]

array([[ 5, 10]])

In [43]:
# Getting individual element value
my_mat[1][0]

20

In [45]:
my_mat[1,0]

30

In [41]:
# 2D array slicing

#Shape (2,2) from top right corner
my_mat[:2,1:]

array([[10, 15],
       [25, 30]])

## Selection

We can use brackets for selection based on comparison of elements

In [43]:
new_arr= np.arange(0,40,5)
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [44]:
new_arr>10

array([False, False, False,  True,  True,  True,  True,  True])

In [45]:
new_arr<20

array([ True,  True,  True,  True, False, False, False, False])

In [46]:
new_arr[new_arr>12]

array([15, 20, 25, 30, 35])

In [47]:
k= 9
new_arr[new_arr<k]

array([0, 5])