# NumPy 

NumPy is a Linear Algebra Library for Python. The reason it is so important for Data Science with Python is that almost all of the libraries in the Python-Data Ecosystem rely on NumPy as one of their main building blocks.

Numpy is extremely fast and useful for all matrix manipulation problems. Image processing and Computer vision are areas of advanced application.

## Using NumPy

Once you've installed NumPy you can import it as a library.
Numpy comes with Anaconda distribution of python by default, so you are good to go if you have Anaconda installed

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We cant't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

NumPy arrays are the main way we use Numpy in data science. Numpy arrays come in two ways: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices can be 2-dimensional (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
sample_list = [1,2,3,4,5,6]
sample_list

[1, 2, 3, 4, 5, 6]

In [3]:
np.array(sample_list)

array([1, 2, 3, 4, 5, 6])

In [6]:
sample_list2 =['a',1,2,3,'f']
np.array(sample_list2)

array(['a', '1', '2', '3', 'f'], dtype='<U1')

In [4]:
sample_matrix = [[10,20,30],[40,50,60],[70,80,90]]
sample_matrix

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [5]:
np.array(sample_matrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
sample_tuple = (3,6,9)
sample_tuple

(3, 6, 9)

In [8]:
np.array(sample_tuple)

array([3, 6, 9])

In [9]:
sample_dict ={0:10,1:20,2:30,3:40,4:50}

In [10]:
np.array(tuple(sample_dict.keys()))

array([0, 1, 2, 3, 4])

In [11]:
np.array(tuple(sample_dict.values()))

array([10, 20, 30, 40, 50])

What if we want to return a collection of key-value pairs in our dictionary?

In [12]:
np.array(list(sample_dict.items()))

array([[ 0, 10],
       [ 1, 20],
       [ 2, 30],
       [ 3, 40],
       [ 4, 50]])

In [7]:
my_dict={'ade':10,'bola':20,'tolu':30}
np.array(list(my_dict.items()))

array([['ade', '10'],
       ['bola', '20'],
       ['tolu', '30']], dtype='<U4')

## Built-in Methods

There are lots of built-in methods in Numpy, we will consider the most used ones

### arange

Returns evenly spaced values within a given interval. It has a default interval of 1

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### linspace
Returns evenly spaced numbers over a specified interval.It takes three arguments. The low and high as well as the number of items to return. The low and high are inclusive.

In [5]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``

In [10]:
np.random.rand(4)

array([0.7986032 , 0.68188607, 0.48445535, 0.74616241])

### randint

returns random integer from interval [low, high) Returns one integer by default unless size is specified

In [25]:
np.random.randint(3)

1

In [11]:
# size argument specifies the number of items to return
np.random.randint(1,7, size=5)

array([5, 5, 6, 1, 6])

### choice

returns a random sample from a given array. By default it returns just one sample

In [13]:
np.random.choice([0,1])

1

In [30]:
np.random.choice([1,2,3,4,5,6],size=5)

array([1, 2, 3, 3, 2])

### nan

This is a numpy constant. In computing, not a number is a numeric data type that can be interpreted as a value that is undefined. We can use " not a number " to represent missing or null values in a dataset. Unfortunately, dirty data sets contain null values with other denominations (e.g. Unknown, — , and n/a), making it difficult to detect and drop them.

In [15]:
nanarray= np.repeat(np.nan,5)
nanarray

array([nan, nan, nan, nan, nan])

### zeros and ones

Generate arrays of zeros or ones. It can only take one argument which can be an integer or a tuple

In [37]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [18]:
array = np.arange(25)
# the code below will generate 10 random integers between 0 and 50
ranarray = np.random.randint(0,50,10)

In [19]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarray

array([29,  0, 32, 36, 10, 19, 12, 13, 39, 36])

## Reshape

Returns an array containing the same data with a new shape.
Consider the total number of values!

In [21]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [22]:
ranarray.max()

39

In [23]:
ranarray.argmax()

8

In [24]:
ranarray.min()

0

In [25]:
ranarray.argmin()

1

## Shape

This is an attribute of an array and not a method

In [26]:
array.shape

(25,)

In [27]:
# method reshape changes the shape of an array to a newly specified shape 
array.reshape(1,25,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]]])

In [51]:
array.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
# attribute shape returns the shape of an array. It is differnt from reshape which is a method that modifies the array shape 
array.reshape(25,1).shape

(25, 1)

In [53]:
#attribute to specify the data type in an array
array.dtype

dtype('int32')